### ISSUE TITLE
Addon registers too many CVars

### ISSUE THREAD

**Issue by Spriithy** [Ko0z/UnitFramesImproved_Vanilla#35]
You are using CVars for a lot of things that could be SavedVariables... This makes WoW alert it and refuses to create them. 

You should really just use Saved Variables :)

good idea tho

**Comment by Ko0z** [comment]
Hey, yea I only started messing with CVar's as an experiment. I've not run into the error with to many CVars but I dont use many other addons so that's logical... 

I will go through all the variables and make those who doesnt need to be CVar's just simple saved variables soon. Thanks for reporting!!

**Comment by Ko0z** [comment]
This should be fixed in v1.0
