### ISSUE TITLE
Nothing working.

### ISSUE THREAD

**Issue by ghost** [Ko0z/UnitFramesImproved_Vanilla#39]
I am using Mod UI

https://i.imgur.com/INxHE61.jpg

Chat freams fucked, chat in game is fucked, NONE of the options work 

So im using a version of this addon, that has many MOD UI things implemented... This wont work with MOD UI ?

https://i.imgur.com/GKM7vPU.jpg

One im usin gatm that works.

**Comment by Ko0z** [comment]
@Skysize Yea, It was compatible with ModUI not so long ago, but since addons get updated frequently, they sometimes end up conflicting one another. I dont have the time unfortunately to check each and every update ModUI gets to check for compatibility issues so therefore I've removed the statement "modUI compatible".

However, UFI shouldn't be the cause for your chat issues since UFI has no chat modifying code. That might be some of your other addons...
